name: Renovate

on:
  schedule:
    - cron: '* */6 * * *'  # Runs every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate Bot
        uses: renovatebot/github-action@v41.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: debug
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
